name: pre-release build
run-name: pre-release build by @${{ github.actor }}
on: push
jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 15
    steps:
    - name: Checkout
      uses: actions/checkout@v2
      with:
        fetch-depth: 0

    - name: Install GitVersion
      uses: gittools/actions/gitversion/setup@v0.9.7
      with:
        versionSpec: '5.10.3'

    - name: Determine Version
      uses: gittools/actions/gitversion/execute@v0.9.7
      with:
        useConfigFile: true

    - name: Build
      run: dotnet build --configuration Release /p:Version=${GITVERSION_NUGETVERSIONV2} src/DnDCharacterSheets.csproj

    - name: Pack
      run: dotnet pack --configuration Release /p:Version=${GITVERSION_NUGETVERSIONV2} --no-build --output .

    # - name: AuthenticateNuget
    #   run: dotnet nuget add source --username USERNAME --password ${{ secrets.NUGET_API_KEY }} --store-password-in-clear-text --name nuget-push "https://api.nuget.org/v3/index.json"

    - name: Push
      run: dotnet nuget push DnDCharacterSheets.${GITVERSION_NUGETVERSIONV2}.nupkg --api-key ${{ secrets.NUGET_API_KEY }} --source https://api.nuget.org/v3/index.json